from dataclasses import dataclass
from typing import Optional

@dataclass
class EDPObject:
        EmplID: Optional[str] = None
        Empl_RCD: Optional[str] = None
        IDIR_EmplID: Optional[str] = None # IDIR employeeID
        IDIR_Userid: Optional[str] = None # IDIR sAMAccountName
        bcGUID: Optional[str] = None #IDIR bcgovGUID
        Empl_Status: Optional[str] = None
        ABCEmployeeRule: Optional[str] = None #PSA Rule1
        PSANonPSARule: Optional[str] = None #PSA Rule2
        miscAppRule: Optional[str] = None #PSA Rule3
        activeEmployeeRule: Optional[str] = None #PSA Rule4
        specialCasesRule: Optional[str] = None #PSA Rule5
        contactInformationFlag: Optional[str] = None #PSA Rule12
        executiveClassificationFlag: Optional[str] = None #PSA Rule13
        Duplicate: Optional[str] = None
        PSA: Optional[str] = None
        EFFDT: Optional[str] = None
        ORG: Optional[str] = None
        IDIR_Mail_org: Optional[str] = None # IDIR mailboxOrgCode
        businessUnitNumber: Optional[str] = None #PSA BU
        BusinessUnit: Optional[str] = None
        Organization: Optional[str] = None
        Level1: Optional[str] = None
        Level2: Optional[str] = None
        Level3: Optional[str] = None
        Level4: Optional[str] = None
        Sector: Optional[str] = None
        DeptID: Optional[str] = None
        Department: Optional[str] = None
        Name: Optional[str] = None
        FirstName: Optional[str] = None
        LastName: Optional[str] = None
        Email: Optional[str] = None
        idirEmail: Optional[str] = None #IDIR mail
        idirPhone: Optional[str] = None #IDIR telephoneNumber
        Phone: Optional[str] = None
        idirStreet: Optional[str] = None #IDIR streetAddress
        idirPostal: Optional[str] = None # IDIR postalCode
        idirCity: Optional[str] = None #IDIR l
        WorkAddress1: Optional[str] = None
        WorkAddress2: Optional[str] = None
        WorkAddress3: Optional[str] = None
        WorkAddress4: Optional[str] = None
        WorkPostalCode: Optional[str] = None
        WorkProv: Optional[str] = None
        PersonalAddress1: Optional[str] = None
        PersonalAddress2: Optional[str] = None
        PersonalAddress3: Optional[str] = None
        PersonalAddress4: Optional[str] = None
        PersonalCity: Optional[str] = None
        PersonalPostalCode: Optional[str] = None
        PersonalProv: Optional[str] = None
        WorkCity: Optional[str] = None
        WorkDevelopmentRegion: Optional[str] = None
        WorkLocationGroup: Optional[str] = None
        WorkLovation: Optional[str] = None
        WorkRegionalDistrict: Optional[str] = None
        personalRegion: Optional[str] = None #PSA WorkDevelopmentRegion
        regionalDistrict: Optional[str] = None #PSA WorkRegionalDistrict
        economicalDevRegion: Optional[str] = None #PSA WorkLocationGroup
        Business_Title: Optional[str] = None
        Position_NBR: Optional[str] = None
        Position_Descr: Optional[str] = None
        ClassificationGroup: Optional[str] = None
        OccupationalGroup: Optional[str] = None
        STEP: Optional[str] = None
        GRADE: Optional[str] = None
        Jobcode: Optional[str] = None
        Jobcode_Descr: Optional[str] = None
        JobCodeDescGroup: Optional[str] = None
        Function_CD: Optional[str] = None
        FunctionDescription: Optional[str] = None
        Empl_CTG: Optional[str] = None
        EmployeeCategoryType: Optional[str] = None
        EmployeeCategoryShortDesc: Optional[str] = None
        EmployeeStatusDesc: Optional[str] = None
        Sal_Admin_Plan: Optional[str] = None
        Sal_Admin_Plan_Decsr: Optional[str] = None
        FulltimeParttime_JobData: Optional[str] = None
        FulltimeParttime_Calculated: Optional[str] = None
        IncludedExcluded: Optional[str] = None
        STD_Hours: Optional[str] = None
        Union_CD: Optional[str] = None
        Union_CD_Descr: Optional[str] = None
        NOC_Code: Optional[str] = None
        NOC_Code_Descr: Optional[str] = None
        NOC_Code_EFF_STATUS: Optional[str] = None
        NOC_Code_EFF_STATUS_DESCR: Optional[str] = None
        NOC_Code_Occ_Group: Optional[str] = None
        Base_Jobcode: Optional[str] = None
        Base_Jobcode_Descr: Optional[str] = None
        Base_Function_CD: Optional[str] = None
        Base_Function_CD_Descr: Optional[str] = None
        Base_Position_NBR: Optional[str] = None
        Base_Step: Optional[str] = None
        Base_Grade: Optional[str] = None
        Base_SAL_ADMIN_PLAN: Optional[str] = None
        Base_EFFDT: Optional[str] = None
        Age: Optional[str] = None
        Age_Group_2: Optional[str] = None
        RegStartAge: Optional[str] = None
        RegStartDate: Optional[str] = None
        MinStartAge: Optional[str] = None
        MinStartDate: Optional[str] = None
        OrigHireDate: Optional[str] = None
        HireDate: Optional[str] = None
        HireAge: Optional[str] = None
        CmpnySeniorityAge: Optional[str] = None
        ServiceDate: Optional[str] = None
        ServiceAge: Optional[str] = None
        CmpnySeniorityDate: Optional[str] = None
        Action: Optional[str] = None
        Action_Descr: Optional[str] = None
        Action_Reason: Optional[str] = None
        Action_Reason_Descr: Optional[str] = None
        Action_Date: Optional[str] = None
        LeaveAccrualDate: Optional[str] = None
        SEQ: Optional[str] = None
        EFFSEQ: Optional[str] = None
        BirthDate: Optional[str] = None
        flagEmail: Optional[str] = None
        MissmatchAddress: Optional[str] = None #Flag 1
        InActiveDirectory: Optional[str] = None # Flag 2
        HR_Status: Optional[str] = None
        Sex: Optional[str] = None
        MultipleRecordsAD: Optional[str] = None # Flag 3
    